version: '3'

services:
    rabbitmq_server:
        image: rabbitmq:management
        ports:
        - "5672:5672"
        - "15672:15672"
    mobius_server:
        image: rencinrig/mobius-spring:1.0.0-SNAPSHOT
        environment:
            MOBIUS_HOME : /code/
        ports:
        - "8080:8080"
        volumes:
        - "./mobius.log:/code/mobius.log"
        - "/Users/komalthareja/mobius/config/application.properties:/code/config/application.properties"

