- name: Configuration to avoid 'Device or resource busy' (CentOS/RedHat)
  when:
    - _docker_os_dist == "CentOS" or _docker_os_dist == "RedHat"
    - ansible_kernel is version_compare('4', '<')
  ansible.builtin.include_tasks: bug-tweaks/bug-centos7-resource-busy.yml
