provider:
  - fabric:
    - fabric_provider:
       - oc-host: orchestrator.fabric-testbed.net
         cm-host: cm.fabric-testbed.net
         bastion-host: bastion-1.fabric-testbed.net
         project_id: REPLACE_ME 
         token-location: REPLACE_ME
         bastion-user-name: REPLACE_ME
         bastion-key-location: REPLACE_ME
         slice-private-key-location: REPLACE_ME
         slice-public-key-location:  REPLACE_ME
  - chi:
    - chi_provider:
        - project_name: REPLACE_ME 
          auth_url:
            tacc: https://chi.tacc.chameleoncloud.org:5000/v3
            uc: https://chi.uc.chameleoncloud.org:5000/v3
            kvm: https://kvm.tacc.chameleoncloud.org:5000/v3
            edge: https://chi.edge.chameleoncloud.org:5000/v3
          client_id:
            tacc: keystone-tacc-prod
            uc: keystone-uc-prod
            kvm: keystone-kvm-prod
            edge: keystone-edge-prod
          project_id:
            tacc: a400724e818d40cbba1a5c6b5e714462
            uc: ae76673270164b048b59d3bd30676721
            kvm: a400724e818d40cbba1a5c6b5e714462
            edge:
          user: REPLACE_ME
          password: REPLACE_ME 
          key_pair: REPLACE_ME
          slice-private-key-location: REPLACE_ME 
          slice-public-key-location: REPLACE_ME

resource:
  - slice:
      - fabric_slice:
          - provider: '{{ fabric.fabric_provider }}'
            name: my_slice
  - slice:
      - chi_slice:
          - provider: '{{ chi.chi_provider }}'
            name: my_slice

  - node:
      - fabric_node:
          - slice:  '{{ slice.fabric_slice }}'
            type: VM
            site: 'STAR'
            count: 1
            image: default_rocky_8
            nic_model: NIC_ConnectX_5

  - node:
      - chi_node:
          - slice:  '{{ slice.chi_slice }}'
            type: Baremetal
            site: CHI@UC
            image: CC-Ubuntu20.04
            network: '{{ network.chi_network.network_name }}'
            count: 1 
            flavor:
              name: m1.medium

  - network:
      - chi_network:
          - slice:  '{{ slice.chi_slice }}'
            name: aes_super_stitch_net
            site: CHI@UC
            subnet: "192.168.100.0/24"
            pool_start: 192.168.100.100
            pool_end: 192.168.100.150
            gateway: 192.168.100.1
            stitch_provider: fabric

  - network:
      - fabric_network:
          - slice: '{{ slice.fabric_slice }}'
            site: 'STAR'
            subnet: "192.168.100.0/24"
            pool_start: 192.168.100.200
            pool_end: 192.168.100.250
            vlan: '{{ network.chi_network.vlans}}'
            interface: '{{ node.fabric_node.interfaces }}'
