# Fabric
# https://portal.fabric-testbed.net
# Create and download FABRIC at https://portal.fabric-testbed.net/ via Experiments -> Manage Tokens
# Create a Bastion Key and User FABRIC at https://portal.fabric-testbed.net/ via Experiments -> Manage SSH Keys
fabric:
   bastion-user-name:
   token-location:
   bastion-key-location: 
   project_id: 
   slice-private-key-location:
   slice-public-key-location:

# Chameleon
# https://www.chameleoncloud.org/
# Create a CLI Password as described here: https://chameleoncloud.readthedocs.io/en/latest/technical/cli.html
# Project Name can be found https://www.chameleoncloud.org/
chi:
   project_name:
   key_pair:
   user:
   password:
   slice-private-key-location:
   slice-public-key-location:

# https://sense-o.es.net:8443/StackV-web/portal/
sense:
   AUTH_ENDPOINT: https://sense-o.es.net:8543/auth/realms/StackV/protocol/openid-connect/token
   API_ENDPOINT: https://sense-o-dev.es.net:8443/StackV-web/restapi
   CLIENT_ID: StackV
   USERNAME:
   PASSWORD:
   SECRET:
   verify: False


janus:
   url: https://x.x.x.x:5000
   username:
   password:
   token:

# Cloudlab
# https://cloudlab.us
# Create an account and join project fabfed
# Must download certificate and reference it below
cloudlab:
  project:
  certificate:
  user:
  slice-private-key-location:
