fabric:
   bastion-user-name:
   token-location:
   bastion-key-location: 
   project_id: 
   slice-private-key-location:
   slice-public-key-location:

chi:
   project_name:
   key_pair:
   user:
   password:
   slice-private-key-location:
   slice-public-key-location:
