config:
  - layer3:
      - layer3:
          subnet:  required
          gateway:
          ip_start:
          ip_end:

  - peering:
      - peering:
          cloud_account: required for aws

          local_device:
          local_port:
          cloud_region:

          cloud_bw:
          cloud_vlan:

          local_asn: required
          local_address: required
          remote_asn: required
          remote_address: required
resource:
  - node:
      - node:
          provider: required
          network:
          site:
          flavor:
          image:
          nic_model:
          name:
          count:  
  - network:
      - net:
          provider:
          layer3:
          peering:
          profile:
          stitch_with:
          name:
          bw:
          count:
