fabric:
  stitch-port:
      - site: AWS
        name: AGG4
        member-of:
          - AWS
        region:
        device_name: agg4.ashb.net.internet2.edu
        local_name: HundredGigE0/0/0/7
        preference: 100 # higher is preferred
      - site: AWS
        member-of:
          - AWS
        region:
        device_name: agg3.ashb.net.internet2.edu
        local_name: TenGigE0/0/0/11/3
        preference: 200 # higher is preferred
  group:
      - name: AWS
        producer-for:
          - sense/AWS
        consumer-for:
          - sense/AWS

      - name: UTAH
        consumer-for:
          - cloudlab/UTAH

      - name: STAR
        consumer-for:
            - chi/STAR

      - name: UKY
        consumer-for:
            - sense/UKY
sense:
  stitch-port:
    - site: UKY
      member-of:
        - UKY
      device_name: UKY-AL2S
      preference: 90 # higher is preferred

  group:
      - name: AWS # referred to as "sense/aws"
        profile: FABRIC-AWS-DX-VGW # SENSE profile name
        consumer-for:
          - fabric/AWS
        producer-for:
          - fabric/AWS
      - name: UKY
        profile: FABRIC-L2-DTN
        maniftest_template:
        option:
            interface:
              - id: urn:ogf:network:al2s.internet2.net:oess:node+core1.loui.net.internet2.edu:port+HundredGigE0_0_0_24
                bandwidth: "500"

        producer-for:
          - fabric/UKY
chi:
  stitch-port:
    - site: STAR
      member-of:
        - STAR
      device_name: Chameleon-StarLight
      preference: 100 # higher is preferred

  group:
    - name: STAR
      producer-for:
        - fabric/STAR

cloudlab:
  stitch-port:
      - site: UTAH
        member-of:
          - UTAH
        device_name: Utah-Cloudlab-Powder
        preference: 100 # higher is preferred
  group:
    - name: UTAH
      profile: fabfed-stitch-v2
      producer-for:
        - fabric/UTAH
