provider:
  - fabric:
    - fabric_provider:
       - credential_file: ~/.fabfed/fabfed_credentials.yml
         profile: fabric
  - chi:
    - chi_provider:
        - credential_file: ~/.fabfed/fabfed_credentials.yml
          profile: chi
resource:
  - slice:
      - fabric_slice:
          - provider: '{{ fabric.fabric_provider }}'
            name: '{{ var.slice_name }}'
  - slice:
      - chi_slice:
          - provider: '{{ chi.chi_provider }}'
            name: '{{ var.slice_name }}'

  - node:
      - fabric_node:
          - slice:  '{{ slice.fabric_slice }}'
            type: VM
            site: 'STAR'
            count: 1
            image: default_rocky_8
            nic_model: NIC_ConnectX_5

  - node:
      - chi_node:
          - slice:  '{{ slice.chi_slice }}'
            type: Baremetal
            site: CHI@UC
            image: CC-Ubuntu20.04
            network: '{{ network.chi_network.network_name }}'
            count: 1 
            flavor: m1.medium

  - network:
      - chi_network:
          - slice:  '{{ slice.chi_slice }}'
            name: aes_super_stitch_net
            site: CHI@UC
            subnet: "192.168.100.0/24"
            pool_start: 192.168.100.100
            pool_end: 192.168.100.150
            gateway: 192.168.100.1
            stitch_provider: fabric

  - network:
      - fabric_network:
          - slice: '{{ slice.fabric_slice }}'
            site: 'STAR'
            subnet: "192.168.100.0/24"
            pool_start: 192.168.100.200
            pool_end: 192.168.100.250
            vlan: '{{ network.chi_network.vlans}}'
            interface: '{{ node.fabric_node.interfaces }}'
