---

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

packages_to_remove:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
  - docker-python
