name: Build And Test 

on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  fabfed_image: fabfed:cicd

jobs:
  DockerBuildAndTest:
    runs-on: ubuntu-22.04
    steps:
      - name: Save Credentials 
        run: |
          mkdir creds
          echo "${{ secrets.FABRIC_TOKEN }}" > creds/token.json
          ls -l creds/token.json

