name: Ubuntu22.04 Modify Test 

on:
  push:
     branches:
      - knit8 
  workflow_dispatch:

env:
  FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
  FABRIC_BASTION_KEY: ${{ secrets.FABRIC_BASTION_KEY }}
  FABRIC_SLIVER_KEY: ${{ secrets.FABRIC_SLIVER_KEY }}
  FABRIC_SLIVER_PUBKEY: ${{ secrets.FABRIC_SLIVER_PUBKEY }}
  FABRIC_PROJECT: ${{ secrets.FABRIC_PROJECT }}
  FABRIC_USER: ${{ secrets.FABRIC_USER }}

jobs:
  UbuntuModifyTest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fabfed And Requirements 
        run: |
          pip install --upgrade pip 
          pip install setuptools --upgrade
          pip install --no-cache-dir --ignore-requires-python neo4j==5.18.0
          pip list -v | grep neo4j
          pip install --no-cache-dir --ignore-requires-python -r requirements.txt
          python3 -m pip install --no-cache-dir .
          pip install --no-cache-dir git+https://gitlab.flux.utah.edu/stoller/portal-tools.git

      - name: Save Credentials
        run: |
          mkdir -p ${{ github.workspace }}/creds
          echo ${{ env.FABRIC_TOKEN }} | base64 --decode > ${{ github.workspace }}/creds/token.json
          echo ${{ env.FABRIC_BASTION_KEY }} | base64 --decode > ${{ github.workspace }}/creds/bastion
          echo ${{ env.FABRIC_SLIVER_KEY }} | base64 --decode > ${{ github.workspace }}/creds/sliver
          echo ${{ env.FABRIC_SLIVER_PUBKEY }} | base64 --decode > ${{ github.workspace }}/creds/sliver.pub

      - name: Test Fabric Modify with FacilityPort 0 nodes
        run: |
          export DO_NOT_DESTROY=1
          session=cicd-fabric-facility-port
          echo "vlan: 3103" > $session-varfile.yml
          echo "node_count: 0" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml

      - name: Test Fabric Modify with FacilityPort Add One Node
        run: |
          export DO_NOT_DESTROY=1
          session=cicd-fabric-facility-port
          echo "vlan: 3103" > $session-varfile.yml
          echo "node_count: 1" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml

      - name: Test Fabric Modify with FacilityPort Add Another Node
        run: |
          export DO_NOT_DESTROY=1
          session=cicd-fabric-facility-port
          echo "vlan: 3103" > $session-varfile.yml
          echo "node_count: 2" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml

      - name: Test Fabric Modify with FacilityPort Remove One Node
        run: |
          export DO_NOT_DESTROY=1
          session=cicd-fabric-facility-port
          echo "vlan: 3103" > $session-varfile.yml
          echo "node_count: 1" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml

      - name: Test Fabric Modify with FacilityPort Remove One Node
        run: |
          export DO_NOT_DESTROY=1
          session=cicd-fabric-facility-port
          echo "vlan: 3103" > $session-varfile.yml
          echo "node_count: 0" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml

      - name: Test Fabric Modify with FacilityPort Destroy 
        run: |
          export DO_NOT_DESTROY=0
          session=cicd-fabric-facility-port
          echo "vlan: 3103" > $session-varfile.yml
          echo "node_count: 0" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml
