name: Ubuntu22.04 Test 

on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  fabfed_image: fabfed:cicd
  FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
  FABRIC_BASTION_KEY: ${{ secrets.FABRIC_BASTION_KEY }}
  FABRIC_SLIVER_KEY: ${{ secrets.FABRIC_SLIVER_KEY }}
  FABRIC_SLIVER_PUBKEY: ${{ secrets.FABRIC_SLIVER_PUBKEY }}

jobs:
  UbuntuTest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Versions 
        run: |
          python3 --version
          pip --version
          pwd
          whoami
          echo ${{ github.workspace }}
          echo $HOME

      - name: Install Fabfed And Requirements 
        run: |
          pip install --upgrade pip 
          pip install setuptools --upgrade
          pip install --no-cache-dir --ignore-requires-python neo4j==5.18.0
          pip list -v | grep neo4j
          pip install --no-cache-dir --ignore-requires-python -r requirements.txt
          python3 -m pip install --no-cache-dir .

      - name: Run Unit Tests
        run: |
          pytest tests

      - name: Test Stitch Policy
        run: |
          fabfed stitch-policy -providers "chi,fabric"

      - name: Show Sessions 
        run: |
          fabfed sessions -show 
          fabfed sessions -show -json
