name: Ubuntu22.04 Test 

on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
  FABRIC_BASTION_KEY: ${{ secrets.FABRIC_BASTION_KEY }}
  FABRIC_SLIVER_KEY: ${{ secrets.FABRIC_SLIVER_KEY }}
  FABRIC_SLIVER_PUBKEY: ${{ secrets.FABRIC_SLIVER_PUBKEY }}
  FABRIC_PROJECT: ${{ secrets.FABRIC_PROJECT }}
  FABRIC_USER: ${{ secrets.FABRIC_USER }}

  SENSE_USER: ${{ secrets.SENSE_USER }}
  SENSE_PASSWORD: ${{ secrets.SENSE_PASSWORD }}
  SENSE_SECRET: ${{ secrets.SENSE_SECRET }}
  SENSE_SLIVER_KEY: ${{ secrets.SENSE_SLIVER_KEY }}

  CLAB_USER: ${{ secrets.CLAB_USER }}
  CLAB_SLIVER_KEY: ${{ secrets.CLAB_SLIVER_KEY }}
  CLAB_PEM_FILE: ${{ secrets.CLAB_PEM_FILE }}
  
  RUN_FABRIC_AWS_SENSE: ${{ vars.RUN_FABRIC_AWS_SENSE }}
  RUN_CLAB: ${{ vars.RUN_CLAB }}
  RUN_FABRIC_AWS_WITH_NODES:  ${{ vars.RUN_FABRIC_AWS_WITH_NODES }}

jobs:
  UbuntuTest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Versions 
        run: |
          python3 --version
          pip --version
          pwd
          whoami
          echo ${{ github.workspace }}
          echo $HOME

      - name: Install Fabfed And Requirements 
        run: |
          pip install --upgrade pip 
          pip install setuptools --upgrade
          pip install --no-cache-dir --ignore-requires-python neo4j==5.18.0
          pip list -v | grep neo4j
          pip install --no-cache-dir --ignore-requires-python -r requirements.txt
          python3 -m pip install --no-cache-dir .
          pip install --no-cache-dir git+https://gitlab.flux.utah.edu/stoller/portal-tools.git

      - name: Run Unit Tests
        run: |
          pytest tests

      - name: Test Stitch Policy
        run: |
          fabfed stitch-policy -providers "chi,fabric"
          fabfed stitch-policy -providers "cloudlab,fabric"
          fabfed stitch-policy -providers "aws,fabric"
          fabfed stitch-policy -providers "gcp,fabric"

      - name: Show Sessions 
        run: |
          fabfed sessions -show 
          fabfed sessions -show -json

      - name: Save Credentials
        run: |
          mkdir -p ${{ github.workspace }}/creds
          echo ${{ env.FABRIC_TOKEN }} | base64 --decode > ${{ github.workspace }}/creds/token.json
          echo ${{ env.FABRIC_BASTION_KEY }} | base64 --decode > ${{ github.workspace }}/creds/bastion
          echo ${{ env.FABRIC_SLIVER_KEY }} | base64 --decode > ${{ github.workspace }}/creds/sliver
          echo ${{ env.FABRIC_SLIVER_PUBKEY }} | base64 --decode > ${{ github.workspace }}/creds/sliver.pub
          echo ${{ env.SENSE_SLIVER_KEY }} | base64 --decode > ${{ github.workspace }}/creds/sense
          echo ${{ env.CLAB_SLIVER_KEY }} | base64 --decode > ${{ github.workspace }}/creds/cloudlab
          echo ${{ env.CLAB_PEM_FILE }} | base64 --decode > ${{ github.workspace }}/creds/cloudlab.pem

      - name: Test Cloudlab
        # if: ${{ env.RUN_CLAB == 'true' }}
        if: false
        run: |
          session=cicd-clab
          echo "site: CLEM" > $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/cloudlab $session $session-varfile.yml

      - name: Test Fabric FacilityPort
        # if: ${{ env.RUN_FABRIC_AWS_SENSE == 'false' || env.RUN_FABRIC_AWS_SENSE == false }} 
        # need to allow for this after changes made for fabric as middle
        if: false
        run: |
          session=cicd-fabric-facility-port
          echo "vlan: 3102" > $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_facility_port $session $session-varfile.yml

      - name: Test L2VPN with nodes.
        # if: ${{ env.RUN_FABRIC_AWS_SENSE == 'false' || env.RUN_FABRIC_AWS_SENSE == false }} 
        if: false
        run: |
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_l2_vpn cicd-fabric-l2-vpn

      - name: Test Fabric AWS (Fabric Only With No Nodes)
        if: false
        run: |
          session=aes-aws-native-no-nodes
          echo "vlan: 7" > $session-varfile.yml
          echo "node_count: 0" >> $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_native_aws $session $session-varfile.yml

      - name: Test Fabric AWS (Fabric Only With Nodes)
        # if: ${{ env.RUN_FABRIC_AWS_WITH_NODES == 'true' || env.RUN_FABRIC_AWS_WITH_NODES == true }} 
        if: false
        run: |
          session=aes-aws-native-with-nodes
          echo "vlan: 7" > $session-varfile.yml
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_native_aws $session $session-varfile.yml

      - name: Test SENSE/AWS.
        # if: ${{ env.RUN_FABRIC_AWS_SENSE == 'true' || env.RUN_FABRIC_AWS_SENSE == true  }} 
        if: false
        run: |
          ${{ github.workspace }}/cicd/run-fabfed.sh cicd/test_configs/fabric_sense_aws cicd-sense-aws 
