name: Ubuntu22.04 Test 

on:
  push:
    branches:
      - develop 
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  fabfed_image: fabfed:cicd
  FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
  FABRIC_BASTION_KEY: ${{ secrets.FABRIC_BASTION_KEY }}
  FABRIC_SLIVER_KEY: ${{ secrets.FABRIC_SLIVER_KEY }}
  FABRIC_SLIVER_PUBKEY: ${{ secrets.FABRIC_SLIVER_PUBKEY }}

jobs:
  UbuntuTest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Versions 
        run: |
          python3 --version
          pip --version
          whoami

      - name: Upgrade 
        run: |
          sudo apt-get update 
          sudo apt-get -u -y install lsb-release python3 binutils python3-venv python3-pip wget git
          python3 --version
          pip --version
          whoami

      - name: Install Neo
        run: |
          pip install --no-cache-dir --ignore-requires-python neo4j
          pip list -v | grep neo4j

      - name: Install requirements 
        run: |
          pip install --no-cache-dir --ignore-requires-python -r requirements.txt
